# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

  # Comment the next line if you're not using Swift and don't want to use dynamic 
  use_frameworks!

  # Pods for Frontend

  target 'Frontend' do
    pod 'Alamofire', '~> 4.7'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'SwiftWebSocket'
    pod 'JSQMessagesViewController'
  end
  target 'FrontendUITests' do
    inherit! :search_paths
    # Pods for testing
  end
